- name: Update package from source list
  apt:
    update_cache: True
  tags: base

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - python3-pip
    - python-setuptools
    - virtualenv
    - unzip
    - openjdk-8-jdk
    - whois
    - libtool
    - bc
    - autotools-dev
    - autoconf
  tags: base

- name: Set timedatectl to Asia/Jakarta
  command: timedatectl set-timezone Asia/Jakarta
  tags: base
