- name: Provision Instance Jenkins Machine
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create instance jenkins
      gce:
        name: "{{ jenkins_name }}"
        zone: "{{ jenkins_region }}"
        external_ip: "none"
        machine_type: "{{ jenkins_machine_type }}"
        image: "{{ jenkins_base_image }}"
        network: "{{ network }}"
        subnetwork: "{{ jenkins_subnetwork }}"
        service_account_permissions:
          - compute-rw
          - storage-ro
          - monitoring-write
          - logging-write
          - cloud-platform
        tags: jenkins
      register: gce_instance_jenkins

#    - name: Save host data
#      add_host:
#        hostname: "{{ item.public_ip }}"
#        groupname: gce_instances_ips
#      with_items: "{{ gce_instance_jenkins.instance_data }}"

#    - name: Wait for SSH to come up
#      wait_for: 
#        host: "{{ item.public_ip }}"
#        port: 22
#        delay: 10
#        timeout: 300
#      with_items: "{{ gce_instance_jenkins.instance_data }}"
