- name: Adds certbot repo
  apt_repository:
    repo: 'ppa:certbot/certbot'
    update_cache: yes
    state: present
    validate_certs: False
  tags: certbot

- name: Install certbot
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
      - python-certbot-nginx
  tags: certbot
