- name: Install docker from ubuntu Repository
  apt:
    name: docker.io
    state: latest
  tags: docker

- name: Start docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes
  tags: docker

- name: pip install docker
  pip:
    name: docker
    state: latest
  tags: docker

- name: pip install docker-py
  pip:
    name: docker-py
    state: absent
  tags: docker
