- name: Add Jenkins apt key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    state: present
  tags: jenkins

- name: Add Jenkins repo
  apt_repository:
    repo: "deb http://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: "jenkins"
    update_cache: yes
  tags: jenkins

- name: Install Jenkins
  apt:
    name: jenkins
    state: latest
  tags: jenkins
