- include_tasks: config.yml
  tags: thumbor-web

- name: Copy thumbor startup script
  template:
    src: service-startup.sh.j2
    dest: /opt/startup-thumbor-web.sh
    owner: root
    group: root
    mode: 0755
  tags: thumbor-web

- name: Copy crossdomain.xml and robots.txt to thumbor instance
  copy:
    src: "{{ item }}"
    dest: "/usr/share/nginx/html/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - thumbor-fallback-image.gif
    - crossdomain.xml
    - robots.txt
  tags: thumbor-web

- name: Obtaining an SSL certificate
  shell: certbot --nginx -d images.{{ domain }} --non-interactive --agree-tos -m {{ email }}
  ignore_errors: yes
  tags: thumbor-web

- name: mkdir archive letsencrypt
  file:
    path: /etc/letsencrypt/archive/
    state: directory
    mode: '0700'
    recurse: yes
    owner: root
    group: root
  tags: thumbor-web

- name: "mkdir {{ domain }} letsencrypt"
  file:
    path: /etc/letsencrypt/archive/images.{{ domain }}.com
    state: directory
    mode: '0755'
    recurse: yes
    owner: root
    group: root
  tags: thumbor-web

- name: mkdir live letsecrypt
  file:
    path: /etc/letsencrypt/live
    state: directory
    mode: '0755'
    recurse: yes
    owner: root
    group: root
  tags: thumbor-web

- name: "mkdir live {{ domain }} letsecrypt"
  file:
    path: /etc/letsencrypt/live/images.{{ domain }}.com
    state: directory
    mode: '0755'
    recurse: yes
    owner: root
    group: root
  tags: thumbor-web

- name: copy ssl key
  shell: gsutil cp gs://{{ domain }}dotcom/ssl/images.{{ domain }}.com/* /etc/letsencrypt/archive/images.{{ domain }}.com/
  tags: thumbor-web

- name: create ssl symbolic link
  file:
    src: "/etc/letsencrypt/archive/images.{{ domain }}.com/{{ item }}"
    dest: " /etc/letsencrypt/live/images.{{ domain }}.com/{{ item }}"
  with_items:
    - privkey2.pem
    - fullchain2.pem
    - chain2.pem
    - cert2.pem
  tags: thumbor-web
